version: 0.0.{build}
skip_non_tags: true
image: Visual Studio 2017
init:
  - ps: |
      $InfoVer = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v");
      $Ver = $InfoVer.Split("-")[0];
      Set-AppveyorBuildVariable -Name "InfomationalVersion" -Value $InfoVer
      Set-AppveyorBuildVariable -Name "FileVersion" -Value $Ver
      Update-AppveyorBuild -Version $InfoVer
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(FileVersion)
  assembly_file_version: $(FileVersion)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(FileVersion)
  package_version: $(InfomationalVersion)
  assembly_version: $(FileVersion)
  file_version: $(FileVersion)
  informational_version: $(InfomationalVersion)
configuration: Release
platform: Any CPU
install:
- ps: .${env:APPVEYOR_BUILD_FOLDER}\AppVeyor\install.ps1
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  access_token:
    secure: Pz30C2oGEq4jlsrbFSRBWxPkmDMdQ0uRxZpKwLZ4yVgBZvrHWxRnnT4WFEI7KVyC
  TestMgmtServer:
    secure: lx9LiOygrkHhoWjTcLWbAg==
  TestMgmtUser:
    secure: G+bmyM6HBj6hQg0noejtiQ==
  TestMgmtPassword:
    secure: UKr8fXGiH9zNRamDDEjKpg==
  TestCertificateHash: FEEAF0B7E97E8EA693EB55B0CF26406351EA0EF5
  TestMgmtName: r8020
  TestIAGateway:
    secure: lx9LiOygrkHhoWjTcLWbAg==
  TestIASecret:
    secure: UKr8fXGiH9zNRamDDEjKpg==
  TestIACertificateHash: FEEAF0B7E97E8EA693EB55B0CF26406351EA0EF5
  TEST_SECRET:
    secure: psHf9gzh1NdoPBovCWs+VzQL9AILX7vy+tD73K6gjkMFHHxeFSGU0iChiPAMRqwH
  APPVEYOR_RDP_PASSWORD:
    secure: ffiKvwUIVY4Ps169F1N1Uw==
test:
  assemblies:
    only:
      - Tests.dll
artifacts:
  - path: 'src\**\*.nupkg'
    name: NuGetPackage
  - path: src\bin\$(configuration)
    name: CheckPoint.NET
    type: zip
  - path: 'docs'
    name: Documentation
    type: zip
deploy:
- provider: NuGet
  api_key:
    secure: XTaEl0O07W12itVzJjGIhoYCy1huW9IfT7gK78rsyn5c/L6qhfCP6y4vYFZQu+6n
  artifact: NuGetPackage
- provider: GitHub
  auth_token:
    secure: Pz30C2oGEq4jlsrbFSRBWxPkmDMdQ0uRxZpKwLZ4yVgBZvrHWxRnnT4WFEI7KVyC
  artifact: CheckPoint.NET
  draft: true
  force_update: true
after_deploy:
  - ps: .${env:APPVEYOR_BUILD_FOLDER}\AppVeyor\Update_gh-pages.ps1
