version: 0.1.{build}
skip_non_tags: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
configuration: Release
platform: Any CPU
install:
- ps: .\AppVeyor_Install.ps1
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  GitToken:
    secure: Pz30C2oGEq4jlsrbFSRBWxPkmDMdQ0uRxZpKwLZ4yVgBZvrHWxRnnT4WFEI7KVyC
  TestMgmtServer:
    secure: UCJ1RE6XfDNrlnauuyM7wQ==
  TestMgmtUser:
    secure: G+bmyM6HBj6hQg0noejtiQ==
  TestMgmtPassword:
    secure: j5oFpdeVkXe0izAo73pe6Q==
test:
  assemblies:
    only:
      - Tests.dll
artifacts:
  - path: 'src\**\*.nupkg'
    name: NuGetPackage
  - path: src\bin\$(configuration)
    name: CheckPoint.NET
    type: zip
  - path: 'docs'
    name: Documentation
    type: zip
deploy:
#- provider: NuGet
#  api_key:
#    secure: 7t1digdSmIqoH3Fl+QikPfgNn1IyFiFBNZxla2qmk0fQCH1pRqd3J6AQ4iJboUDV
#  artifact: NuGetPackage
#  on:
#    branch: master
- provider: GitHub
  auth_token:
    secure: Pz30C2oGEq4jlsrbFSRBWxPkmDMdQ0uRxZpKwLZ4yVgBZvrHWxRnnT4WFEI7KVyC
  artifact: CheckPoint.NET
  draft: true
  force_update: true
  on:
    branch: master
after_deploy:
- ps: .\AppVeyor_Deploy_gh-pages.ps1